/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutUsRouteImport } from './routes/aboutUs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyPagesIndexRouteImport } from './routes/myPages/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as MyPages9RouteImport } from './routes/myPages/9'
import { Route as MyPages8RouteImport } from './routes/myPages/8'
import { Route as MyPages7RouteImport } from './routes/myPages/7'
import { Route as MyPages6RouteImport } from './routes/myPages/6'
import { Route as MyPages5RouteImport } from './routes/myPages/5'
import { Route as MyPages4RouteImport } from './routes/myPages/4'
import { Route as MyPages3RouteImport } from './routes/myPages/3'
import { Route as MyPages2RouteImport } from './routes/myPages/2'
import { Route as MyPages19RouteImport } from './routes/myPages/19'
import { Route as MyPages18RouteImport } from './routes/myPages/18'
import { Route as MyPages17RouteImport } from './routes/myPages/17'
import { Route as MyPages16RouteImport } from './routes/myPages/16'
import { Route as MyPages15RouteImport } from './routes/myPages/15'
import { Route as MyPages14RouteImport } from './routes/myPages/14'
import { Route as MyPages13RouteImport } from './routes/myPages/13'
import { Route as MyPages12RouteImport } from './routes/myPages/12'
import { Route as MyPages11RouteImport } from './routes/myPages/11'
import { Route as MyPages10RouteImport } from './routes/myPages/10'
import { Route as HomeSliderScrollRouteImport } from './routes/home/sliderScroll'
import { Route as HomeSliderAnimationsRouteImport } from './routes/home/sliderAnimations'
import { Route as HomeSlider3dRouteImport } from './routes/home/slider3d'
import { Route as Home7RouteImport } from './routes/home/7'
import { Route as Home6RouteImport } from './routes/home/6'
import { Route as Home5RouteImport } from './routes/home/5'
import { Route as Home4RouteImport } from './routes/home/4'
import { Route as Home3RouteImport } from './routes/home/3'
import { Route as Home2RouteImport } from './routes/home/2'
import { Route as Explore9RouteImport } from './routes/explore/9'
import { Route as Explore8RouteImport } from './routes/explore/8'
import { Route as Explore7RouteImport } from './routes/explore/7'
import { Route as Explore6RouteImport } from './routes/explore/6'
import { Route as Explore5RouteImport } from './routes/explore/5'
import { Route as Explore4RouteImport } from './routes/explore/4'
import { Route as Explore3RouteImport } from './routes/explore/3'
import { Route as Explore2RouteImport } from './routes/explore/2'
import { Route as Blog5RouteImport } from './routes/blog/5'
import { Route as Blog4RouteImport } from './routes/blog/4'
import { Route as Blog3RouteImport } from './routes/blog/3'
import { Route as Blog2RouteImport } from './routes/blog/2'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/aboutUs',
  path: '/aboutUs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPagesIndexRoute = MyPagesIndexRouteImport.update({
  id: '/myPages/',
  path: '/myPages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages9Route = MyPages9RouteImport.update({
  id: '/myPages/9',
  path: '/myPages/9',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages8Route = MyPages8RouteImport.update({
  id: '/myPages/8',
  path: '/myPages/8',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages7Route = MyPages7RouteImport.update({
  id: '/myPages/7',
  path: '/myPages/7',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages6Route = MyPages6RouteImport.update({
  id: '/myPages/6',
  path: '/myPages/6',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages5Route = MyPages5RouteImport.update({
  id: '/myPages/5',
  path: '/myPages/5',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages4Route = MyPages4RouteImport.update({
  id: '/myPages/4',
  path: '/myPages/4',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages3Route = MyPages3RouteImport.update({
  id: '/myPages/3',
  path: '/myPages/3',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages2Route = MyPages2RouteImport.update({
  id: '/myPages/2',
  path: '/myPages/2',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages19Route = MyPages19RouteImport.update({
  id: '/myPages/19',
  path: '/myPages/19',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages18Route = MyPages18RouteImport.update({
  id: '/myPages/18',
  path: '/myPages/18',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages17Route = MyPages17RouteImport.update({
  id: '/myPages/17',
  path: '/myPages/17',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages16Route = MyPages16RouteImport.update({
  id: '/myPages/16',
  path: '/myPages/16',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages15Route = MyPages15RouteImport.update({
  id: '/myPages/15',
  path: '/myPages/15',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages14Route = MyPages14RouteImport.update({
  id: '/myPages/14',
  path: '/myPages/14',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages13Route = MyPages13RouteImport.update({
  id: '/myPages/13',
  path: '/myPages/13',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages12Route = MyPages12RouteImport.update({
  id: '/myPages/12',
  path: '/myPages/12',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages11Route = MyPages11RouteImport.update({
  id: '/myPages/11',
  path: '/myPages/11',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPages10Route = MyPages10RouteImport.update({
  id: '/myPages/10',
  path: '/myPages/10',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSliderScrollRoute = HomeSliderScrollRouteImport.update({
  id: '/home/sliderScroll',
  path: '/home/sliderScroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSliderAnimationsRoute = HomeSliderAnimationsRouteImport.update({
  id: '/home/sliderAnimations',
  path: '/home/sliderAnimations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSlider3dRoute = HomeSlider3dRouteImport.update({
  id: '/home/slider3d',
  path: '/home/slider3d',
  getParentRoute: () => rootRouteImport,
} as any)
const Home7Route = Home7RouteImport.update({
  id: '/home/7',
  path: '/home/7',
  getParentRoute: () => rootRouteImport,
} as any)
const Home6Route = Home6RouteImport.update({
  id: '/home/6',
  path: '/home/6',
  getParentRoute: () => rootRouteImport,
} as any)
const Home5Route = Home5RouteImport.update({
  id: '/home/5',
  path: '/home/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Home4Route = Home4RouteImport.update({
  id: '/home/4',
  path: '/home/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Home3Route = Home3RouteImport.update({
  id: '/home/3',
  path: '/home/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Home2Route = Home2RouteImport.update({
  id: '/home/2',
  path: '/home/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore9Route = Explore9RouteImport.update({
  id: '/explore/9',
  path: '/explore/9',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore8Route = Explore8RouteImport.update({
  id: '/explore/8',
  path: '/explore/8',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore7Route = Explore7RouteImport.update({
  id: '/explore/7',
  path: '/explore/7',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore6Route = Explore6RouteImport.update({
  id: '/explore/6',
  path: '/explore/6',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore5Route = Explore5RouteImport.update({
  id: '/explore/5',
  path: '/explore/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore4Route = Explore4RouteImport.update({
  id: '/explore/4',
  path: '/explore/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore3Route = Explore3RouteImport.update({
  id: '/explore/3',
  path: '/explore/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore2Route = Explore2RouteImport.update({
  id: '/explore/2',
  path: '/explore/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog5Route = Blog5RouteImport.update({
  id: '/blog/5',
  path: '/blog/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog4Route = Blog4RouteImport.update({
  id: '/blog/4',
  path: '/blog/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog3Route = Blog3RouteImport.update({
  id: '/blog/3',
  path: '/blog/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog2Route = Blog2RouteImport.update({
  id: '/blog/2',
  path: '/blog/2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/blog/2': typeof Blog2Route
  '/blog/3': typeof Blog3Route
  '/blog/4': typeof Blog4Route
  '/blog/5': typeof Blog5Route
  '/explore/2': typeof Explore2Route
  '/explore/3': typeof Explore3Route
  '/explore/4': typeof Explore4Route
  '/explore/5': typeof Explore5Route
  '/explore/6': typeof Explore6Route
  '/explore/7': typeof Explore7Route
  '/explore/8': typeof Explore8Route
  '/explore/9': typeof Explore9Route
  '/home/2': typeof Home2Route
  '/home/3': typeof Home3Route
  '/home/4': typeof Home4Route
  '/home/5': typeof Home5Route
  '/home/6': typeof Home6Route
  '/home/7': typeof Home7Route
  '/home/slider3d': typeof HomeSlider3dRoute
  '/home/sliderAnimations': typeof HomeSliderAnimationsRoute
  '/home/sliderScroll': typeof HomeSliderScrollRoute
  '/myPages/10': typeof MyPages10Route
  '/myPages/11': typeof MyPages11Route
  '/myPages/12': typeof MyPages12Route
  '/myPages/13': typeof MyPages13Route
  '/myPages/14': typeof MyPages14Route
  '/myPages/15': typeof MyPages15Route
  '/myPages/16': typeof MyPages16Route
  '/myPages/17': typeof MyPages17Route
  '/myPages/18': typeof MyPages18Route
  '/myPages/19': typeof MyPages19Route
  '/myPages/2': typeof MyPages2Route
  '/myPages/3': typeof MyPages3Route
  '/myPages/4': typeof MyPages4Route
  '/myPages/5': typeof MyPages5Route
  '/myPages/6': typeof MyPages6Route
  '/myPages/7': typeof MyPages7Route
  '/myPages/8': typeof MyPages8Route
  '/myPages/9': typeof MyPages9Route
  '/blog': typeof BlogIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/myPages': typeof MyPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/blog/2': typeof Blog2Route
  '/blog/3': typeof Blog3Route
  '/blog/4': typeof Blog4Route
  '/blog/5': typeof Blog5Route
  '/explore/2': typeof Explore2Route
  '/explore/3': typeof Explore3Route
  '/explore/4': typeof Explore4Route
  '/explore/5': typeof Explore5Route
  '/explore/6': typeof Explore6Route
  '/explore/7': typeof Explore7Route
  '/explore/8': typeof Explore8Route
  '/explore/9': typeof Explore9Route
  '/home/2': typeof Home2Route
  '/home/3': typeof Home3Route
  '/home/4': typeof Home4Route
  '/home/5': typeof Home5Route
  '/home/6': typeof Home6Route
  '/home/7': typeof Home7Route
  '/home/slider3d': typeof HomeSlider3dRoute
  '/home/sliderAnimations': typeof HomeSliderAnimationsRoute
  '/home/sliderScroll': typeof HomeSliderScrollRoute
  '/myPages/10': typeof MyPages10Route
  '/myPages/11': typeof MyPages11Route
  '/myPages/12': typeof MyPages12Route
  '/myPages/13': typeof MyPages13Route
  '/myPages/14': typeof MyPages14Route
  '/myPages/15': typeof MyPages15Route
  '/myPages/16': typeof MyPages16Route
  '/myPages/17': typeof MyPages17Route
  '/myPages/18': typeof MyPages18Route
  '/myPages/19': typeof MyPages19Route
  '/myPages/2': typeof MyPages2Route
  '/myPages/3': typeof MyPages3Route
  '/myPages/4': typeof MyPages4Route
  '/myPages/5': typeof MyPages5Route
  '/myPages/6': typeof MyPages6Route
  '/myPages/7': typeof MyPages7Route
  '/myPages/8': typeof MyPages8Route
  '/myPages/9': typeof MyPages9Route
  '/blog': typeof BlogIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/myPages': typeof MyPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/blog/2': typeof Blog2Route
  '/blog/3': typeof Blog3Route
  '/blog/4': typeof Blog4Route
  '/blog/5': typeof Blog5Route
  '/explore/2': typeof Explore2Route
  '/explore/3': typeof Explore3Route
  '/explore/4': typeof Explore4Route
  '/explore/5': typeof Explore5Route
  '/explore/6': typeof Explore6Route
  '/explore/7': typeof Explore7Route
  '/explore/8': typeof Explore8Route
  '/explore/9': typeof Explore9Route
  '/home/2': typeof Home2Route
  '/home/3': typeof Home3Route
  '/home/4': typeof Home4Route
  '/home/5': typeof Home5Route
  '/home/6': typeof Home6Route
  '/home/7': typeof Home7Route
  '/home/slider3d': typeof HomeSlider3dRoute
  '/home/sliderAnimations': typeof HomeSliderAnimationsRoute
  '/home/sliderScroll': typeof HomeSliderScrollRoute
  '/myPages/10': typeof MyPages10Route
  '/myPages/11': typeof MyPages11Route
  '/myPages/12': typeof MyPages12Route
  '/myPages/13': typeof MyPages13Route
  '/myPages/14': typeof MyPages14Route
  '/myPages/15': typeof MyPages15Route
  '/myPages/16': typeof MyPages16Route
  '/myPages/17': typeof MyPages17Route
  '/myPages/18': typeof MyPages18Route
  '/myPages/19': typeof MyPages19Route
  '/myPages/2': typeof MyPages2Route
  '/myPages/3': typeof MyPages3Route
  '/myPages/4': typeof MyPages4Route
  '/myPages/5': typeof MyPages5Route
  '/myPages/6': typeof MyPages6Route
  '/myPages/7': typeof MyPages7Route
  '/myPages/8': typeof MyPages8Route
  '/myPages/9': typeof MyPages9Route
  '/blog/': typeof BlogIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/myPages/': typeof MyPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutUs'
    | '/contact'
    | '/blog/2'
    | '/blog/3'
    | '/blog/4'
    | '/blog/5'
    | '/explore/2'
    | '/explore/3'
    | '/explore/4'
    | '/explore/5'
    | '/explore/6'
    | '/explore/7'
    | '/explore/8'
    | '/explore/9'
    | '/home/2'
    | '/home/3'
    | '/home/4'
    | '/home/5'
    | '/home/6'
    | '/home/7'
    | '/home/slider3d'
    | '/home/sliderAnimations'
    | '/home/sliderScroll'
    | '/myPages/10'
    | '/myPages/11'
    | '/myPages/12'
    | '/myPages/13'
    | '/myPages/14'
    | '/myPages/15'
    | '/myPages/16'
    | '/myPages/17'
    | '/myPages/18'
    | '/myPages/19'
    | '/myPages/2'
    | '/myPages/3'
    | '/myPages/4'
    | '/myPages/5'
    | '/myPages/6'
    | '/myPages/7'
    | '/myPages/8'
    | '/myPages/9'
    | '/blog'
    | '/explore'
    | '/home'
    | '/myPages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutUs'
    | '/contact'
    | '/blog/2'
    | '/blog/3'
    | '/blog/4'
    | '/blog/5'
    | '/explore/2'
    | '/explore/3'
    | '/explore/4'
    | '/explore/5'
    | '/explore/6'
    | '/explore/7'
    | '/explore/8'
    | '/explore/9'
    | '/home/2'
    | '/home/3'
    | '/home/4'
    | '/home/5'
    | '/home/6'
    | '/home/7'
    | '/home/slider3d'
    | '/home/sliderAnimations'
    | '/home/sliderScroll'
    | '/myPages/10'
    | '/myPages/11'
    | '/myPages/12'
    | '/myPages/13'
    | '/myPages/14'
    | '/myPages/15'
    | '/myPages/16'
    | '/myPages/17'
    | '/myPages/18'
    | '/myPages/19'
    | '/myPages/2'
    | '/myPages/3'
    | '/myPages/4'
    | '/myPages/5'
    | '/myPages/6'
    | '/myPages/7'
    | '/myPages/8'
    | '/myPages/9'
    | '/blog'
    | '/explore'
    | '/home'
    | '/myPages'
  id:
    | '__root__'
    | '/'
    | '/aboutUs'
    | '/contact'
    | '/blog/2'
    | '/blog/3'
    | '/blog/4'
    | '/blog/5'
    | '/explore/2'
    | '/explore/3'
    | '/explore/4'
    | '/explore/5'
    | '/explore/6'
    | '/explore/7'
    | '/explore/8'
    | '/explore/9'
    | '/home/2'
    | '/home/3'
    | '/home/4'
    | '/home/5'
    | '/home/6'
    | '/home/7'
    | '/home/slider3d'
    | '/home/sliderAnimations'
    | '/home/sliderScroll'
    | '/myPages/10'
    | '/myPages/11'
    | '/myPages/12'
    | '/myPages/13'
    | '/myPages/14'
    | '/myPages/15'
    | '/myPages/16'
    | '/myPages/17'
    | '/myPages/18'
    | '/myPages/19'
    | '/myPages/2'
    | '/myPages/3'
    | '/myPages/4'
    | '/myPages/5'
    | '/myPages/6'
    | '/myPages/7'
    | '/myPages/8'
    | '/myPages/9'
    | '/blog/'
    | '/explore/'
    | '/home/'
    | '/myPages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  Blog2Route: typeof Blog2Route
  Blog3Route: typeof Blog3Route
  Blog4Route: typeof Blog4Route
  Blog5Route: typeof Blog5Route
  Explore2Route: typeof Explore2Route
  Explore3Route: typeof Explore3Route
  Explore4Route: typeof Explore4Route
  Explore5Route: typeof Explore5Route
  Explore6Route: typeof Explore6Route
  Explore7Route: typeof Explore7Route
  Explore8Route: typeof Explore8Route
  Explore9Route: typeof Explore9Route
  Home2Route: typeof Home2Route
  Home3Route: typeof Home3Route
  Home4Route: typeof Home4Route
  Home5Route: typeof Home5Route
  Home6Route: typeof Home6Route
  Home7Route: typeof Home7Route
  HomeSlider3dRoute: typeof HomeSlider3dRoute
  HomeSliderAnimationsRoute: typeof HomeSliderAnimationsRoute
  HomeSliderScrollRoute: typeof HomeSliderScrollRoute
  MyPages10Route: typeof MyPages10Route
  MyPages11Route: typeof MyPages11Route
  MyPages12Route: typeof MyPages12Route
  MyPages13Route: typeof MyPages13Route
  MyPages14Route: typeof MyPages14Route
  MyPages15Route: typeof MyPages15Route
  MyPages16Route: typeof MyPages16Route
  MyPages17Route: typeof MyPages17Route
  MyPages18Route: typeof MyPages18Route
  MyPages19Route: typeof MyPages19Route
  MyPages2Route: typeof MyPages2Route
  MyPages3Route: typeof MyPages3Route
  MyPages4Route: typeof MyPages4Route
  MyPages5Route: typeof MyPages5Route
  MyPages6Route: typeof MyPages6Route
  MyPages7Route: typeof MyPages7Route
  MyPages8Route: typeof MyPages8Route
  MyPages9Route: typeof MyPages9Route
  BlogIndexRoute: typeof BlogIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MyPagesIndexRoute: typeof MyPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutUs': {
      id: '/aboutUs'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/': {
      id: '/myPages/'
      path: '/myPages'
      fullPath: '/myPages'
      preLoaderRoute: typeof MyPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/9': {
      id: '/myPages/9'
      path: '/myPages/9'
      fullPath: '/myPages/9'
      preLoaderRoute: typeof MyPages9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/8': {
      id: '/myPages/8'
      path: '/myPages/8'
      fullPath: '/myPages/8'
      preLoaderRoute: typeof MyPages8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/7': {
      id: '/myPages/7'
      path: '/myPages/7'
      fullPath: '/myPages/7'
      preLoaderRoute: typeof MyPages7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/6': {
      id: '/myPages/6'
      path: '/myPages/6'
      fullPath: '/myPages/6'
      preLoaderRoute: typeof MyPages6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/5': {
      id: '/myPages/5'
      path: '/myPages/5'
      fullPath: '/myPages/5'
      preLoaderRoute: typeof MyPages5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/4': {
      id: '/myPages/4'
      path: '/myPages/4'
      fullPath: '/myPages/4'
      preLoaderRoute: typeof MyPages4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/3': {
      id: '/myPages/3'
      path: '/myPages/3'
      fullPath: '/myPages/3'
      preLoaderRoute: typeof MyPages3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/2': {
      id: '/myPages/2'
      path: '/myPages/2'
      fullPath: '/myPages/2'
      preLoaderRoute: typeof MyPages2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/19': {
      id: '/myPages/19'
      path: '/myPages/19'
      fullPath: '/myPages/19'
      preLoaderRoute: typeof MyPages19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/18': {
      id: '/myPages/18'
      path: '/myPages/18'
      fullPath: '/myPages/18'
      preLoaderRoute: typeof MyPages18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/17': {
      id: '/myPages/17'
      path: '/myPages/17'
      fullPath: '/myPages/17'
      preLoaderRoute: typeof MyPages17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/16': {
      id: '/myPages/16'
      path: '/myPages/16'
      fullPath: '/myPages/16'
      preLoaderRoute: typeof MyPages16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/15': {
      id: '/myPages/15'
      path: '/myPages/15'
      fullPath: '/myPages/15'
      preLoaderRoute: typeof MyPages15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/14': {
      id: '/myPages/14'
      path: '/myPages/14'
      fullPath: '/myPages/14'
      preLoaderRoute: typeof MyPages14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/13': {
      id: '/myPages/13'
      path: '/myPages/13'
      fullPath: '/myPages/13'
      preLoaderRoute: typeof MyPages13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/12': {
      id: '/myPages/12'
      path: '/myPages/12'
      fullPath: '/myPages/12'
      preLoaderRoute: typeof MyPages12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/11': {
      id: '/myPages/11'
      path: '/myPages/11'
      fullPath: '/myPages/11'
      preLoaderRoute: typeof MyPages11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myPages/10': {
      id: '/myPages/10'
      path: '/myPages/10'
      fullPath: '/myPages/10'
      preLoaderRoute: typeof MyPages10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/sliderScroll': {
      id: '/home/sliderScroll'
      path: '/home/sliderScroll'
      fullPath: '/home/sliderScroll'
      preLoaderRoute: typeof HomeSliderScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/sliderAnimations': {
      id: '/home/sliderAnimations'
      path: '/home/sliderAnimations'
      fullPath: '/home/sliderAnimations'
      preLoaderRoute: typeof HomeSliderAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/slider3d': {
      id: '/home/slider3d'
      path: '/home/slider3d'
      fullPath: '/home/slider3d'
      preLoaderRoute: typeof HomeSlider3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/7': {
      id: '/home/7'
      path: '/home/7'
      fullPath: '/home/7'
      preLoaderRoute: typeof Home7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/6': {
      id: '/home/6'
      path: '/home/6'
      fullPath: '/home/6'
      preLoaderRoute: typeof Home6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/5': {
      id: '/home/5'
      path: '/home/5'
      fullPath: '/home/5'
      preLoaderRoute: typeof Home5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/4': {
      id: '/home/4'
      path: '/home/4'
      fullPath: '/home/4'
      preLoaderRoute: typeof Home4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/3': {
      id: '/home/3'
      path: '/home/3'
      fullPath: '/home/3'
      preLoaderRoute: typeof Home3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/2': {
      id: '/home/2'
      path: '/home/2'
      fullPath: '/home/2'
      preLoaderRoute: typeof Home2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/9': {
      id: '/explore/9'
      path: '/explore/9'
      fullPath: '/explore/9'
      preLoaderRoute: typeof Explore9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/8': {
      id: '/explore/8'
      path: '/explore/8'
      fullPath: '/explore/8'
      preLoaderRoute: typeof Explore8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/7': {
      id: '/explore/7'
      path: '/explore/7'
      fullPath: '/explore/7'
      preLoaderRoute: typeof Explore7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/6': {
      id: '/explore/6'
      path: '/explore/6'
      fullPath: '/explore/6'
      preLoaderRoute: typeof Explore6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/5': {
      id: '/explore/5'
      path: '/explore/5'
      fullPath: '/explore/5'
      preLoaderRoute: typeof Explore5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/4': {
      id: '/explore/4'
      path: '/explore/4'
      fullPath: '/explore/4'
      preLoaderRoute: typeof Explore4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/3': {
      id: '/explore/3'
      path: '/explore/3'
      fullPath: '/explore/3'
      preLoaderRoute: typeof Explore3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/2': {
      id: '/explore/2'
      path: '/explore/2'
      fullPath: '/explore/2'
      preLoaderRoute: typeof Explore2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/5': {
      id: '/blog/5'
      path: '/blog/5'
      fullPath: '/blog/5'
      preLoaderRoute: typeof Blog5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/4': {
      id: '/blog/4'
      path: '/blog/4'
      fullPath: '/blog/4'
      preLoaderRoute: typeof Blog4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/3': {
      id: '/blog/3'
      path: '/blog/3'
      fullPath: '/blog/3'
      preLoaderRoute: typeof Blog3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/2': {
      id: '/blog/2'
      path: '/blog/2'
      fullPath: '/blog/2'
      preLoaderRoute: typeof Blog2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  Blog2Route: Blog2Route,
  Blog3Route: Blog3Route,
  Blog4Route: Blog4Route,
  Blog5Route: Blog5Route,
  Explore2Route: Explore2Route,
  Explore3Route: Explore3Route,
  Explore4Route: Explore4Route,
  Explore5Route: Explore5Route,
  Explore6Route: Explore6Route,
  Explore7Route: Explore7Route,
  Explore8Route: Explore8Route,
  Explore9Route: Explore9Route,
  Home2Route: Home2Route,
  Home3Route: Home3Route,
  Home4Route: Home4Route,
  Home5Route: Home5Route,
  Home6Route: Home6Route,
  Home7Route: Home7Route,
  HomeSlider3dRoute: HomeSlider3dRoute,
  HomeSliderAnimationsRoute: HomeSliderAnimationsRoute,
  HomeSliderScrollRoute: HomeSliderScrollRoute,
  MyPages10Route: MyPages10Route,
  MyPages11Route: MyPages11Route,
  MyPages12Route: MyPages12Route,
  MyPages13Route: MyPages13Route,
  MyPages14Route: MyPages14Route,
  MyPages15Route: MyPages15Route,
  MyPages16Route: MyPages16Route,
  MyPages17Route: MyPages17Route,
  MyPages18Route: MyPages18Route,
  MyPages19Route: MyPages19Route,
  MyPages2Route: MyPages2Route,
  MyPages3Route: MyPages3Route,
  MyPages4Route: MyPages4Route,
  MyPages5Route: MyPages5Route,
  MyPages6Route: MyPages6Route,
  MyPages7Route: MyPages7Route,
  MyPages8Route: MyPages8Route,
  MyPages9Route: MyPages9Route,
  BlogIndexRoute: BlogIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MyPagesIndexRoute: MyPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
